name: ConvAI → Master Doc (каждые 5 минут)

on:
  schedule:
    # срабатывает каждые 5 минут
    - cron: '*/5 * * * *'

jobs:
  convai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # важно для пуша back last_run.txt
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install google-api-python-client google-auth-oauthlib requests

      - name: Export secrets
        run: |
          echo "MASTER_DOC_ID=${{ secrets.MASTER_DOC_ID }}" >> $GITHUB_ENV

      - name: Run ConvAI → Master Doc
        run: python download_convai_to_master_doc.py

      - name: Commit updated last_run.txt
        run: |
          # проверяем, изменился ли last_run.txt
          if [[ -n "$(git status --porcelain last_run.txt)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add last_run.txt
            git commit -m "chore: update last_run.txt [skip ci]"
            git push
          else
            echo "last_run.txt не изменился — пуш не нужен."
          fi
