name: ConvAI to Master Doc (every 5 minutes)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  convai_sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install google-api-python-client google-auth google-auth-oauthlib requests

    - name: Run script
      env:
        MASTER_DOC_ID: ${{ secrets.MASTER_DOC_ID }}
      run: python download_convai_to_master_doc.py

    - name: Commit updated last_run.txt if changed
      run: |
        git add last_run.txt || true
        if git diff --cached --exit-code --quiet; then
          echo "No changes to commit."
        else
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -m "chore: update last_run.txt [skip ci]"
          git push origin main
