name: ConvAI → Google Docs

on:
  schedule:
    - cron: '* * * * *'    # каждые 5 минут по UTC
  workflow_dispatch:        # ручной запуск из UI

jobs:
  update-doc:
    runs-on: ubuntu-latest
    env:
      MASTER_DOC_ID: ${{ secrets.MASTER_DOC_ID }}
      TZ_OFFSET_HOURS: ${{ secrets.TZ_OFFSET_HOURS }}
    steps:
      - uses: actions/checkout@v3

      - name: Установить Python и зависимости
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install requests google-api-python-client google-auth google-auth-oauthlib

      - name: Запустить скрипт
        run: |
          . venv/bin/activate
          python3 download_convai_to_master_doc.py
